library (MASS)
install.packages("ISLR2")
library (ISLR2)
head (Boston)
lm.fit

lm.fit <- lm(medv ??? lstat , data = Boston)
attach (Boston)
lm.fit <- lm(medv ??? lstat)
summary(lm.fit)
lm(formula = medv ??? lstat)
names (lm.fit)
coef (lm.fit)
confint (lm.fit)
predict(lm.fit, data.frame(lstat= (c(5, 10, 15))),interval ="confidence")
predict(lm.fit, data.frame(lstat = (c(5, 10, 15))),interval ="prediction")
plot (lstat , medv)
abline (lm.fit)
abline (lm.fit , lwd = 3)
abline (lm.fit , lwd = 3, col = " red ")
plot (lstat , medv , col = " red ")
plot (lstat , medv , pch = 20)
plot (lstat , medv , pch = "+")
par (mfrow = c(2, 2))
plot (lm.fit)
plot (hatvalues (lm.fit))
which.max(hatvalues (lm.fit))
plot(predict (lm.fit), residuals (lm.fit))
plot(predict (lm.fit), rstudent (lm.fit))
#On the basis of the residual plots, there is some evidence of non-linearity